    <div id="content" class="cf">
        <div id="sidebar">
            <ul class="list">
                <li class="item"><a href="<?=site_url('index.php/dashboard');?>" title="" class="link ico dashboard<?=($this->uri->segment(1) == 'dashboard')? ' active':'';?>"><?=LNG_MENU_DASHBOARD;?></a></li>
                <li class="item"><a href="<?=site_url('index.php/schedule');?>" title="" class="link ico schedule<?=($this->uri->segment(1) == 'schedule')? ' active':'';?>"><?=LNG_MENU_SCHEDULES;?></a></li>
                <li class="item"><a href="<?=site_url('index.php/groups');?>" title="" class="link ico users<?=($this->uri->segment(1) == 'groups')? ' active':'';?>"><?=LNG_MENU_GROUPS;?></a></li>
<?php
    if($check_admin)
    {
?>
                <li class="item"><a href="<?=site_url('index.php/users');?>" title="" class="link ico users<?=($this->uri->segment(1) == 'users')? ' active':'';?>"><?=LNG_MENU_USERS;?></a></li>
<?php
    }
?>
                <li class="item"><a href="<?=site_url('index.php/settings');?>" title="" class="link ico settings<?=($this->uri->segment(1) == 'settings')? ' active':'';?>"><?=LNG_MENU_SETTINGS;?></a></li>
            </ul>
        </div>
        <div id="general">
            <div class="text">
                <h1>About</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, <a href="#" title="">hic pariatur quis fugit</a> deserunt repellendus dolore sit nulla tempore magni earum maiores <em>ullam aperiam ab ut numquam voluptate eaque soluta</em>! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis <strong>fugit deserunt repellendus</strong> dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!</p>
                <p><img src="content/img_full.jpg" alt=""/>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!</p>
                <p><img class="lt" src="content/img.jpg" alt=""/>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!</p>
                <p><img class="rt" src="content/img.jpg" alt=""/>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!</p>
                <ul>
                    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit</li>
                </ul>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!</p>
                <ol>
                    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem, laboriosam, assumenda, illum aliquid nulla est atque voluptatum earum repellat explicabo blanditiis et iste soluta nostrum quod consequatur vero repudiandae. Deserunt?</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem, laboriosam, assumenda, illum aliquid nulla est atque voluptatum earum repellat explicabo blanditiis et iste soluta nostrum quod consequatur vero repudiandae. Deserunt?</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem, laboriosam, assumenda, illum aliquid nulla est atque voluptatum earum repellat explicabo blanditiis et iste soluta nostrum quod consequatur vero repudiandae. Deserunt?</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem, laboriosam, assumenda, illum aliquid nulla est atque voluptatum earum repellat explicabo blanditiis et iste soluta nostrum quod consequatur vero repudiandae. Deserunt?</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem, laboriosam, assumenda, illum aliquid nulla est atque voluptatum earum repellat explicabo blanditiis et iste soluta nostrum quod consequatur vero repudiandae. Deserunt?</li>
                </ol>
                <h1>Heading 1</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!</p>
                <h2>Heading 2</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!</p>
                <h3>Heading 3</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!</p>
                <h4>Heading 4</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!</p>
                <h5>Heading 5</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!</p>
                <h6>Heading 6</h6>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, hic pariatur quis fugit deserunt repellendus dolore sit nulla tempore magni earum maiores ullam aperiam ab ut numquam voluptate eaque soluta!</p>
            </div>
        </div>
    </div>
